export const LIST_DEPARTMENTS = 'LIST_DEPARTMENTS';
export const CREATE_DEPARTMENTS = 'CREATE_DEPARTMENTS';
export const DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS';
export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';
