export const LIST_DEPARTMENTS   = 'LIST_DEPARTMENTS';
export const CREATE_DEPARTMENTS = 'CREATE_DEPARTMENTS';
export const DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS';
export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';
export const SELECT_DEPARTMENT  = 'SELECT_DEPARTMENT';



export const CREATE_EMPLOYEES = 'CREATE_EMPLOYEES';
export const DELETE_EMPLOYEES = 'DELETE_EMPLOYEES';
export const UPDATE_EMPLOYEES = 'UPDATE_EMPLOYEES';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
